version: '3.8'

services:
  service1:
    build:
      context: ./service1
    container_name: service1
    expose:
      - "8001"

  service2:
    build:
      context: ./service2
    image: flask-backend
    container_name: service2
    expose:
      - "8002"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - service1
      - service2

